#!/bin/bash

### Ajouter les dépots suivants dans /etc/apt/source.list

cp /etc/apt/sources.list /etc/apt/sources.list.backup

echo > /etc/apt/sources.list

cat <<EOT >> /etc/apt/sources.list
deb http://deb.debian.org/debian/ buster main
deb-src http://deb.debian.org/debian/ buster main
deb http://deb.debian.org/debian/ buster-updates main
deb-src http://deb.debian.org/debian/ buster-updates main
deb http://security.debian.org/debian-security buster/updates main
deb-src http://security.debian.org/debian-security buster/updates main
EOT

apt-get update

echo "Mise a jour OK"

apt-get install -y git


# Force Locale

echo "LC_ALL=en_US.UTF-8" >> /etc/default/locale

locale-gen en_US.UTF-8

# Install Some PPAs

apt-get install -y software-properties-common curl

curl --silent --location https://deb.nodesource.com/setup_10.x | bash -


apt-get update

apt-get install -y build-essential dos2unix gcc git libmcrypt4 libpcre3-dev ntp unzip wget \
make python2.7-dev python-pip re2c supervisor unattended-upgrades whois vim libnotify-bin \
pv cifs-utils mcrypt bash-completion zsh

ln -sf /usr/share/zoneinfo/UTC /etc/localtime

echo "Installation des packages de base OK"

apt-get install ufw 

echo "UFW OK"


apt install -y apt-transport-https ca-certificates
wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
sh -c 'echo "deb https://packages.sury.org/php/ buster main" > /etc/apt/sources.list.d/php.list'
apt update
##apt-get -y install libcurl3  ##nécissaire pour l'installation de php7.1-curl 

# Installation Php7.0

####il faut installé au préalable la premiére partie php7.1

apt-get install -y php7.0  php7.0-cli php7.0-common php7.0-opcache php7.0-mbstring php7.0-curl php7.0-mysql php7.0-zip php7.0-xml
echo "PHP-7.0 OK"

/etc/init.d/apache2 stop

apt-get -y remove --purge apache*

# Installation Php7.1
apt install -y php7.1-apcu php7.1-bcmath php7.1-cli php7.1-fpm php7.1-gd php7.1-curl php7.1-intl php7.1-mcrypt php7.1-mysql php7.1-soap php7.1-xml php7.1-zip
echo "PHP-7.1 OK"

# Installation Php7.2
apt-get install -y php7.2 php7.2-cli php7.2-common php7.2-opcache php7.2-mbstring php7.2-curl php7.2-mysql php7.2-zip php7.2-xml
echo "PHP-7.2 OK"

# Installation Php7.4
apt install -y php7.4-common php7.4-mysql php7.4-gmp php7.4-curl php7.4-intl php7.4-mbstring php7.4-xmlrpc php7.4-gd php7.4-xml php7.4-cli php7.4-zip php7.4-soap php7.4-imap
echo "PHP-7.4 OK"

### Commande pour changer de version php 

update-alternatives --set php /usr/bin/php7.4

# Install Php7.1-fpm, Php7.2-fpm et php7.4-fpm  

apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
php7.0-fpm php7.1-fpm php7.2-fpm php7.4-fpm

apt -y autoremove

echo "PHP-FPM OK"

## Installation de Nginx 1.19

sh -c 'echo "deb http://nginx.org/packages/mainline/debian/ buster nginx" > /etc/apt/sources.list.d/nginx.list'

cd /tmp

wget http://nginx.org/keys/nginx_signing.key | apt-key add nginx_signing.key

apt-get update

apt-get install -y nginx

cd /etc/nginx/

mkdir sites-enabled
mkdir sites-available

###ajouter dans le bloc http

sed -i '/^include*/a \include /etc/nginx/sites-enabled/*;' nginx.conf

service nginx restart

echo "Nginx OK"

# Dans le cas oû les répertoires sites-available et sites-enabled n'existe pas il faudra les crées 

# Install Composer

cd /tmp
curl -sS https://getcomposer.org/installer | php
mv composer.phar /usr/local/bin/composer
echo "Composer Ok"

# Installation Mysql 5.7
echo "Merci de changer le mdp root Mysql du script"
apt-get install -y debconf-utils
export DEBIAN_FRONTEND="noninteractive"
debconf-set-selections <<< "mysql-server mysql-server/root_password password timm_01"
debconf-set-selections <<< "mysql-server mysql-server/root_password_again password timm_01"
apt-key adv --keyserver hkp://pool.sks-keyservers.net:80 --recv-keys 8C718D3B5072E1F5 
apt-get update
apt-get -y install mysql-server
echo "Merci d'exécuter la commande #mysql_secure_installation afin de modifier le mdp root de votre installation"
  
####Install PhpMyadmin

# vhost PhpMyadmin avec letsencrypt 

cat <<EOT >> /etc/nginx/sites-available/pma
server {

    # Listen on port 9991
    listen 9991;

    # Server name being used (exact name, wildcards or regular expression)
    server_name pma.mydomain.fr;

    root /usr/share/phpmyadmin;

    # Logging
    error_log /var/log/phpmyadmin.error_log;
    access_log /var/log/phpmyadmin.access_log;


   location / {
           index  index.php;
           #return 301 https://pma.cnge.fr$request_uri;
       }

       ## Images and static content is treated different
           location ~* ^.+.(jpg|jpeg|gif|css|png|js|ico|xml)$ {
           access_log        off;
           expires           360d;
       }

       location ~ /\.ht {
           deny  all;
       }

   #location / {
    #    try_files $uri $uri/ /app_dev.php?$query_string;
     #   return 301 https://pma.cnge.fr$request_uri;
      # }


       location ~ /(libraries|setup/frames|setup/libs) {
           deny all;
           return 404;
}

    # Pass the PHP scripts to FastCGI server
    location ~ \.php$ {

        fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /usr/share/phpmyadmin$fastcgi_script_name;
        fastcgi_param  HTTPS off;
    }

}

echo "Vhost pma OK"

cd /etc/nginx/sites-enabled 
ln -s ../sites-available/pma pma
/etc/init.d/nginx restart

apt install -y php-json php-mbstring
cd /tmp
wget https://files.phpmyadmin.net/phpMyAdmin/4.9.0.1/phpMyAdmin-4.9.0.1-all-languages.tar.gz
tar -zxvf phpMyAdmin-4.9.0.1-all-languages.tar.gz
mv phpMyAdmin-4.9.0.1-all-languages /usr/share/phpmyadmin

echo "Importation PMA OK"
echo "Pour configurer pma suivre le tuto "

echo "Suivre le tuto suivant pour l'installation de phpmyadmin"
echo "https://www.itzgeek.com/how-tos/linux/debian/how-to-install-phpmyadmin-with-nginx-on-debian-10.html"

echo "Configuration UFW"










